# Generated by Django 3.2.20 on 2023-07-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
